name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: C/C++ Linter
        run: echo Running linter
        uses: cpp-linter/cpp-linter-action@v2.6.0
        with:
          thread-comments: true
